services:
  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@127.0.0.1:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - ALLOW_PLAINTEXT_LISTENER=yes

  metabase:
    build: .
    container_name: metabase
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
      MB_PLUGINS_DIR: /plugins
      MB_PLUGINS_FORCE_DOWNLOAD: false
      MB_JDBC_CONNECTION_TIMEOUT: 60000
    volumes:
      - ./metabase-data:/metabase-data
      - /dev/urandom:/dev/random:ro
      - /Users/dhivakarsathya/PycharmProjects/DE_case_study/metabase-data/plugins:/plugins
      - /Users/dhivakarsathya/PycharmProjects/DE_case_study/my_duckbase.duckdb:/metabase-data/mydb.duckdb:rw
    ports:
      - "3000:3000"